### ISSUE TITLE
meme doesn't work on memes with hyphens

### ISSUE THREAD

**Issue by borick** [waynegraham/hubot-memes#14]
in ./src/memes.coffee
regex \w is used for "meme me" line
but it doesn't match hyphens in sad-clinton, etc.
i fixed locally by changing \w to "."
just FYI

**Comment by waynegraham** [comment]
Thanks @borick 

I really need to sit down and crank out the rewrite of all of this soon. 

Mind sending a patch for this?

**Comment by neufeldtech** [comment]
@waynegraham I can try to patch this up (hopefully soon). The parsing error is my fault from here:https://github.com/waynegraham/hubot-memes/commit/86a739e33215d64fdff9da54faeb76b3cf9695bb
